---
title: "Scientific inquiry"
output: html_document
css: style.css
---

## Learning objectives

Students should be able to:

* list the requirements of a well-crafted hypothesis 
* formulate a well-crafted research question and hypothesis based on an observation
* describe the differences between a manipulative experiment and an observational study
* identify independent and dependent variables in an experimental or observational study
* identify experimental and control treatments in an experimental study
* identify natural "experimental" and "control" treatments in an observational study


## Resources

* [Slides 01. Scientific inquiry](https://docs.google.com/presentation/d/1J_MQHerLhh3m3X6Nt_omx3b_K_YBR9RpqcHNmxg37pA/edit?usp=sharing)
* [Milroy Ch 1 p 3-16](https://mrne392.github.io/lesson-plans/readings/Milroy_Ch1.pdf): The foundations of scientific inquiry (slides and learning objectives are largely based on this chapter)
* Papers that go into greater depth on observational vs. experimental ecology (optional)
  * [Sagarin & Pauchard 2010: Observational approaches in ecology open new ground in a changing world](https://mrne392.github.io/lesson-plans/readings/Sagarin_Pauchard_2010.pdf)
  * [Wootton & Pfister 1998: The motivation for and context of experiments in ecology](https://mrne392.github.io/lesson-plans/readings/Wootton_Pfister_1998.pdf)


## Lesson plan

### 1. Introductions

* Share name & preferred pronouns, major(s)/minor(s), something fun or interesting you did this summer.
* In groups: What is field research? Why do we do it? What are your research interests and why?

### 2. Course logistics

* Course website url:[https://mrne392.github.io/website/](https://mrne392.github.io/website/). Bookmark this link - it has everything you need for the class. 
* The [syllabus](https://mrne392.github.io/website/syllabus.html) contains information on assessment and class policies.
* The [schedule](https://mrne392.github.io/website/schedule.html) is our master organizer. All assignments, slides, lab exercises, etc. are linked here by date. 

### 3. Intro to field research and scientific inquiry

<iframe src="https://docs.google.com/presentation/d/1J_MQHerLhh3m3X6Nt_omx3b_K_YBR9RpqcHNmxg37pA/embed?start=false&loop=false&delayms=5000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>

