---
title: "Marsh field methods"
output: html_document
css: style.css
---
## Housekeeping

* We will meet for lab at the vans next to Physical Plant (by the ARC)
* Wear long pants (light, loose-fitting synthetic material is best; avoid jeans and tights). The grass will tear up your legs and the ranger said chiggers are out there too. There's also a small amount of poison ivy.
* Bring waterproof boots (we have extra boots in limited sizes - if you own a pair please bring them). 
* Be prepared to spend most of the afternoon outside. 
* Bring your marsh plants species ID guide to take the field ID quiz.

## Learning objectives

* Articulate and follow standard operating procedures for collecting field data in our marsh field study
* Explain what parameter each measurement is designed to measure and what that parameter will help us test our hypotheses

## Resources

* Slides
* [Milroy Ch 3: Experimental design](https://mrne392.github.io/lesson-plans/readings/Milroy_Ch3.pdf)

## Lesson plan

1. We'll first go over the details of our marsh sampling methods, as outlined in the slides, so that you're ready to make the measurements in the field today. Pay close attention because Kylie and I won't be able to help everyone at the same time.

<iframe src="https://docs.google.com/presentation/d/1V8VrXDSoeyJIivLSKPxECJzmMrDmmyq-bhgUY9I1600/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>

2. Pre-lab prep:

**Enter quadrat coordinates into GPS unit**

* Put a piece of labeling tape on your group's GPS unit and label it with your group letter.  
* Enter your group's [GPS coordinates](https://docs.google.com/spreadsheets/d/1mYoGyq-8Y2-RpsXb-zOX1jk5tfSAcb7muXgy5Yux3so/edit?gid=0#gid=0) into your GPS unit. Make sure to label each coordinate with the correct quadrat number.
* Note: For longitude coordinates, -76 is the same thing as W76

**Pre-label three biomass bags and three sediment sample containers**

* Use a sharpie to put the date, "Point Lookout," your group letter, and quadrat number on each of your three biomass bags
* Use a sharpie to write directly on the sediment sample containers your group letter and quadrat number
