---
title: "SAV sample processing"
output: html_document
css: style.css
---
## Resources

* [Animal datasheet](https://docs.google.com/spreadsheets/d/1v5taHFVVZiA8XPXAbQ4n5857FToXCtW9mN1hfKhdsSI/edit?usp=sharing)
* [SAV species ID guide](https://dnr.maryland.gov/waters/bay/Documents/SAV/complete_sav_key.pdf)

<iframe src="https://docs.google.com/presentation/d/1po_bQO2yl5RPzcE5ENP_fQrvJvtGat8XWUu893FIpd4/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>

## I. Knot-tying 

* Tie a bowline, lobster buoy hitch, and half hitch (instructional videos [here](https://mrne392.github.io/assessment/knot-tying.html))

## II. SAV sample processing instructions

### A few notes about this lab

* **Nobody is done until everyone is done.** If you finish your sample, help someone else finish theirs.
* **Keep track of your sample bag!** It contains your sample ID information. It is very important that you don't misplace your sample bag or get it mixed up with someone else's bag. We need to be able to identify the site and chamber letter for each sample.
* I need to finish these today. If we're not done by the end of lab and you have time to stay to help me finish, I would much appreciate it. If not no worries.

### Instructions

1. Grab a sample bag, dump it into a sieve, and rinse the sample. Fill a plastic container with water and place your sample in the water. Bring the sample, along with the sample bag, back to your bench. 
**Do not dump dirty water down the drain: pour through a sieve first so that we don't clog the drain.**
1. Gently clean the sample. Change the water with fresh water. Repeat until the water stays more or less clear. If there is any algae or calcifying organisms attached to the leaves, carefully scrape them off with your finger.
1. Grab a few smaller tupperwares - one for each species. Separate your plants into the smaller tuperwares by species. Make sure to clean as much of the Lyngbya off the plants as possible. Place the Lyngbya into its own container and clean as much sediment and debris from the Lyngbya as possible. 
1. Separate the above-ground material (leaves, shoots) from the below-ground material (roots and rhizomes) by pinching off the shoots where they meet the roots/rhizomes. 
1. Place the samples into foil packets, separated by species and above/below ground material. Label foil packets with the site name, sample date, species abbreviation (see below), chamber letter, and AG (for above ground) or BG (for belowground).
1. If there are any clams or worms in your sample, place them on a numbered weigh boat. Find your boat number in the [animal datasheet](https://docs.google.com/spreadsheets/d/1v5taHFVVZiA8XPXAbQ4n5857FToXCtW9mN1hfKhdsSI/edit?usp=sharing) and record the river (POT), site (FW or BR), chamber_id (A-L), and species_id (either "clam" or "worm"). You can place more than one clam or worm on a weigh boat if they're small enough to fit but don't put both clams and worms in the same weigh boat. Double check that you recorded your sample ID information in the animsl datasheet, then place the weigh boat on a cookie sheet in the drying oven.
1. If you notice that there are a lot (like more than 10) of another type of animal in your sample, let me know. We may want to dry and weigh them as well.

### Species abbreviations

**Brackish sites**

* RM: Ruppia maritima (widgeon grass)
* ZM: Zostera marina (eelgrass)

**Freshwater sites**

* LW: Lyngbya woleii
* CD: Ceratophyllum demersum (coontail)
* EC: Elodea canadensis (elodea)
* HD: Heteranthera dubia (water stargrass)
* HV: Hydrilla verticillata (hydrilla)
* MS: Myriophyllum spicatum (Eurasian water milfoil)
* NAI: Naiads
* VA: Vallisneria americana (wild celery)
