---
title: "Oceanographic variables"
output: html_document
css: style.css
---
## Housekeeping

* The next quiz (10/24) will be on knot-tying! You'll be quizzed on the knots you'll need to be able to do for our last field study. The knots and instructional videos are listed [here](https://mrne392.github.io/assessment/knot-tying.html). Make sure to bring your rope to class!
* Lab will be inside and outside this week. We'll meet in SH 112.

## Learning objectives

* Define *Lagrangian* and *Eulerian* and explain how these approaches to measuring oceanographic variables differ from each other
* Determine appropriate spatial and temporal boundaries for an oceanographic field study
* Define UTC and be able to convert UTC time to local time
* Define *density* and *hydrostatic pressure*
* Explain how temperature, salinity, and pressure affect density
* Select appropriate physical, chemical, and/or geologic variables to test a given hypothesis

## Resources

* [Slides](https://docs.google.com/presentation/d/1cRkNcJbUjzz59q-NXI2OHHKcrRhgmeDWSBYT244uxfE)
* [Milroy Ch. 4: Oceanographic variables](https://mrne392.github.io/lesson-plans/readings/Milroy_Ch4.pdf)

## Lesson plan

<iframe src="https://docs.google.com/presentation/d/1cRkNcJbUjzz59q-NXI2OHHKcrRhgmeDWSBYT244uxfE/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>
