---
title: "Hydrologic instrument retrieval planning"
output: html_document
css: style.css
---
## Housekeeping

* Quiz Thursday: be able to: describe your field study questions, hypotheses, and objectives; describe your methods; explain how your measurements are designed to test your hypotheses. There is not necessarily a right or wrong answer, I just want to see that you are able to articulate these things.

## Learning objectives

* Determine appropriate methods and supplies needed for field equipment retrieval

## Resources

* [Field study folder](https://drive.google.com/drive/u/0/folders/1wtrXccYT4a-26WlzA1wwQgkIST36K7t7)

## Lesson plan

1. Complete your group's retrieval planning worksheet, available in [Field study folder](https://drive.google.com/drive/u/0/folders/1wtrXccYT4a-26WlzA1wwQgkIST36K7t7)
1. Class discussion: Towards the end of the semester we'll have a class activity in which you'll develop a field research "toolkit" for your future selves and/or other early career field researchers. The purpose of this discussion today is to start thinking about your experiences in this class and reflect on their applicability to your future work in ecological field research.

* What went well in lab last week?
* What didn't go as well and why?
* What can you do differently this week to avoid these challenges?
* What can you do to use your time more efficiently?
* What lessons can you carry forward to future field studies?
* In general, what technical skills/abilities to you need in order to successfully carry out field research?
* In general, what soft skills do you need in order to successfully carry out field research?

