---
title: "Skills and knowledge inventory"
output: html_document
css: style.css
---
## Housekeeping

* Please fill out online course evaluation if you haven't yet
* Poster presentation dry-run in lab today - be ready to present and answer questions
* Poster symposium is Friday in the ARC
    * All posters need to be hung by 10:00 am Friday morning. You should hang your poster on your assigned board. Push pins will be provided in the poster hall.
    * You can look up your board number and presentation time [here](https://docs.google.com/spreadsheets/d/1mh9wwvnB_G9_QXD71zr4qcamEk3v0I3HWuSnIxFPPjY/edit?gid=0#gid=0)
    * Presentations are at either 11:30-12:15 or 12:15-100 to help spread things out. You are responsible for standing next to your poster during your assigned time slot.
    * Attire is "business casual" or "smart casual" - sweats are too casual; however blazers/ties/slacks/nice dresses, etc. are too formal. Don't stress about this - pants/skirt and a sweater, polo, button-down, a casual dress, or something similar will be fine, just don't roll out of bed and show up in your PJ's!  

## Learning objectives

* Reflect on everything you've learned

## Resources

* [Poster board number and schedule spreadsheet](https://docs.google.com/spreadsheets/d/1mh9wwvnB_G9_QXD71zr4qcamEk3v0I3HWuSnIxFPPjY/edit?gid=0#gid=0)

## Lesson plan

<iframe src="https://docs.google.com/presentation/d/1RB4DpNWgyZ4ZZA2K3c2uZyom5My-n5NEeRg2NG67vlI/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true" data-external="1"></iframe>
